name: Deploy nodejs app to ec2
on:
  push:
    branches: ["main"]
jobs:
  build:
    name: building nodejs app
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 22.x
          cache: "npm"

      - name: install depedencies
        run: npm install

      - name: build
        run: npm run build
  deploy:
    name: push code to ec2
    needs: ["build"]
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: executing remote ssh commands
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{secrets.HOST}}
          username: ubuntu
          key: ${{secrets.PRIVATE_SSH_KEY}}
          port: 22
          script: |
            export PATH=$PATH:/usr/local/bin
            cd sample-nodejs-app
            git pull origin main
            npm install
            npm install -g pm2
            npm run build
            pm2 stop nodejs-app || true
            pm2 start npm --name "nodejs-app" -- start
            pm2 save
            pm2 startup
