name: Nodejs app

on:
  push:
    branches:
      - main
jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      #step 1
      - name: Checkout
        uses: actions/checkout@v3

      #step 2
      - name: setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 23.5.0

      #step 3
      - name: install dependencies
        run: npm install

      #step 4
      - name: build 
        run: npm run build
